### ISSUE TITLE
Environment variables not interpolated in test definition variables

### ISSUE THREAD

**Issue by mrfoh** [mrfoh/httpprobe#9]
## Reproduction
```yaml
name: Login Test
description: This test suite checks the login functionality of the service
variables:
  base_url:
    type: string
    value: ${env:BASE_URL}
suites:
  - name: Login
    cases:
      - title: /auth/login
        request:
          method: POST
          url: ${base_url}/auth/login
          headers:
            - key: content-type
              value: application/json
          body:
            type: json
            data: |
              {
                "userName": "${env:LOGIN_EMAIL}",
                "password": "${env:LOGIN_PASSWORD}"
              }
          assertions:
            status: 200
            body:
              $.message: "Logged in successfully !!"
              $.data.access-token: contains eyJ
```

## Error

```
2025-03-14T17:18:32.800Z        ERROR   runner/runner.go:307    Error executing test case       {"title": "/auth/login", "error": "error executing request: error creating request: parse \"${env:CLOUDGATEWAY_URL}/auth/login\": first path segment in URL cannot contain colon"}
```
